<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="1" total="6" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="46234" started-at="2020-03-15T11:12:18 CST" finished-at="2020-03-15T11:13:04 CST">
    <groups>
    </groups>
    <test name="Login validation" duration-ms="32117" started-at="2020-03-15T11:12:18 CST" finished-at="2020-03-15T11:12:50 CST">
      <class name="wizeline.LoginValidation">
        <test-method status="PASS" signature="initialize()[pri:0, instance:wizeline.LoginValidation@396f6598]" name="initialize" is-config="true" duration-ms="9525" started-at="2020-03-15T11:12:18 CST" finished-at="2020-03-15T11:12:27 CST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method status="PASS" signature="Login(java.lang.String, java.lang.String)[pri:0, instance:wizeline.LoginValidation@396f6598]" name="Login" duration-ms="6016" started-at="2020-03-15T11:12:27 CST" data-provider="getData" finished-at="2020-03-15T11:12:33 CST">
          <params>
            <param index="0">
              <value>
                <![CDATA[standard_user]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[secret_sauce]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login -->
        <test-method status="FAIL" signature="Login(java.lang.String, java.lang.String)[pri:0, instance:wizeline.LoginValidation@396f6598]" name="Login" duration-ms="242" started-at="2020-03-15T11:12:33 CST" data-provider="getData" finished-at="2020-03-15T11:12:33 CST">
          <params>
            <param index="0">
              <value>
                <![CDATA[locked_out_user]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[secret_sauce]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[User or password is invalid expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: User or password is invalid expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at wizeline.LoginValidation.Login(LoginValidation.java:50)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login -->
        <test-method status="PASS" signature="Login(java.lang.String, java.lang.String)[pri:0, instance:wizeline.LoginValidation@396f6598]" name="Login" duration-ms="5671" started-at="2020-03-15T11:12:33 CST" data-provider="getData" finished-at="2020-03-15T11:12:39 CST">
          <params>
            <param index="0">
              <value>
                <![CDATA[problem_user]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[secret_sauce]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login -->
        <test-method status="PASS" signature="Login(java.lang.String, java.lang.String)[pri:0, instance:wizeline.LoginValidation@396f6598]" name="Login" duration-ms="10344" started-at="2020-03-15T11:12:39 CST" data-provider="getData" finished-at="2020-03-15T11:12:49 CST">
          <params>
            <param index="0">
              <value>
                <![CDATA[performance_glitch_user]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[secret_sauce]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login -->
        <test-method status="PASS" signature="Login(java.lang.String, java.lang.String)[pri:0, instance:wizeline.LoginValidation@396f6598]" name="Login" duration-ms="238" started-at="2020-03-15T11:12:49 CST" data-provider="getData" finished-at="2020-03-15T11:12:50 CST">
          <params>
            <param index="0">
              <value>
                <![CDATA[negative_scenario]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[negative_scenario]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:wizeline.LoginValidation@396f6598]" name="teardown" is-config="true" duration-ms="35" started-at="2020-03-15T11:12:50 CST" finished-at="2020-03-15T11:12:50 CST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- wizeline.LoginValidation -->
    </test> <!-- Login validation -->
    <test name="Product validation" duration-ms="14095" started-at="2020-03-15T11:12:50 CST" finished-at="2020-03-15T11:13:04 CST">
      <class name="wizeline.ProductsValidation">
        <test-method status="PASS" signature="initialize()[pri:0, instance:wizeline.ProductsValidation@30a3107a]" name="initialize" is-config="true" duration-ms="9776" started-at="2020-03-15T11:12:50 CST" finished-at="2020-03-15T11:12:59 CST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:wizeline.ProductsValidation@30a3107a]" name="teardown" is-config="true" duration-ms="4318" started-at="2020-03-15T11:12:59 CST" finished-at="2020-03-15T11:13:04 CST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- wizeline.ProductsValidation -->
    </test> <!-- Product validation -->
  </suite> <!-- Suite -->
</testng-results>
